/** Human-readable labels for audit log action codes. */
export const AUDIT_LABELS: Record<string, string> = {
  "auth.register": "Account created",
  "auth.login": "Signed in",
  "org.create": "Workspace created",
  "org.rename": "Workspace renamed",
  "member.invited": "Member invited",
  "member.invite.accept": "Invitation accepted",
  "member.invite.revoke": "Invitation revoked",
  "member.role_change": "Member role changed",
  "member.remove": "Member removed",
  "member.suspend": "Member suspended",
  "member.reactivate": "Member reactivated",
  "profile.update": "Profile updated",
  "profile.password_change": "Password changed",

  "lead.create": "Lead created",
  "lead.update": "Lead updated",
  "lead.archive": "Lead archived",
  "lead.unarchive": "Lead restored",
  "lead.convert": "Lead converted",
  "lead.export": "Leads exported",
  "lead.bulk_assign": "Leads reassigned",
  "lead.bulk_status": "Lead statuses changed",
  "lead.bulk_tag": "Leads tagged",
  "lead.bulk_archive": "Leads archived",

  "contact.create": "Contact created",
  "contact.update": "Contact updated",
  "contact.archive": "Contact archived",
  "contact.unarchive": "Contact restored",
  "contact.export": "Contacts exported",

  "company.create": "Company created",
  "company.update": "Company updated",
  "company.archive": "Company archived",
  "company.unarchive": "Company restored",
  "company.address_save": "Company address saved",
  "company.export": "Companies exported",

  "tag.create": "Tag created",
  "tag.update": "Tag updated",
  "tag.delete": "Tag deleted",

  "deal.create": "Deal created",
  "deal.update": "Deal updated",
  "deal.stage_change": "Deal stage changed",
  "deal.won": "Deal won",
  "deal.lost": "Deal lost",
  "deal.archive": "Deal archived",
  "deal.unarchive": "Deal restored",
  "deal.export": "Deals exported",

  "task.create": "Task created",
  "task.update": "Task updated",
  "task.status": "Task status changed",
  "task.delete": "Task deleted",

  "pipeline.create": "Pipeline created",

  "integration.configure": "Integration configured",
  "integration.enable": "Integration enabled",
  "integration.disable": "Integration disabled",
  "integration.disconnect": "Integration disconnected",
  "integration.rotate_webhook_secret": "Webhook secret rotated",
  "integration.quotation.create": "Quotation created via provider",
  "integration.quotation.accepted": "Quotation accepted",
  "integration.quotation.declined": "Quotation declined",
  "integration.quotation.updated": "Quotation updated",
  "integration.invoice.created": "Invoice created",
  "integration.invoice.updated": "Invoice updated",
  "integration.invoice.paid": "Invoice paid",
  "integration.payment.recorded": "Payment recorded",

  "automation.run": "Automation run",
  "automation.rule.create": "Automation rule created",
  "automation.rule.update": "Automation rule updated",
  "automation.rule.enable": "Automation rule enabled",
  "automation.rule.disable": "Automation rule disabled",
  "automation.rule.delete": "Automation rule deleted",

  "report.export": "Report exported",
};
