/** Human-readable labels for audit log action codes. */
export const AUDIT_LABELS: Record<string, string> = {
  "auth.register": "Account created",
  "auth.login": "Signed in",
  "org.create": "Workspace created",
  "org.rename": "Workspace renamed",
  "member.invited": "Member invited",
  "member.invite.accept": "Invitation accepted",
  "member.invite.revoke": "Invitation revoked",
  "member.role_change": "Member role changed",
  "member.remove": "Member removed",
  "member.suspend": "Member suspended",
  "member.reactivate": "Member reactivated",
  "profile.update": "Profile updated",
  "profile.password_change": "Password changed",

  "lead.create": "Lead created",
  "lead.update": "Lead updated",
  "lead.archive": "Lead archived",
  "lead.unarchive": "Lead restored",
  "lead.convert": "Lead converted",
  "lead.export": "Leads exported",
  "lead.bulk_assign": "Leads reassigned",
  "lead.bulk_status": "Lead statuses changed",
  "lead.bulk_tag": "Leads tagged",
  "lead.bulk_archive": "Leads archived",

  "contact.create": "Contact created",
  "contact.update": "Contact updated",
  "contact.archive": "Contact archived",
  "contact.unarchive": "Contact restored",
  "contact.export": "Contacts exported",

  "company.create": "Company created",
  "company.update": "Company updated",
  "company.archive": "Company archived",
  "company.unarchive": "Company restored",
  "company.address_save": "Company address saved",
  "company.export": "Companies exported",

  "tag.create": "Tag created",
  "tag.update": "Tag updated",
  "tag.delete": "Tag deleted",
};
