import type { Metadata } from "next";
import Link from "next/link";
import { ChevronLeft } from "lucide-react";

import { requireOrgContext } from "@/lib/context";
import { can } from "@/lib/rbac";
import { prisma } from "@/lib/db";
import { formatDate } from "@/lib/utils";
import { getInvoiceIntegration } from "@/lib/integrations/invoice";
import { PageHeader } from "@/components/app/page-header";
import { DeniedState } from "@/components/app/denied";
import { Card, CardContent, CardHeader, CardTitle, Badge } from "@/components/ui/primitives";
import { buttonClassName } from "@/components/ui/button";
import { IntegrationForm } from "./integrations-client";
import { setInvoiceEnabledAction, disconnectInvoiceAction } from "./actions";

export const metadata: Metadata = { title: "Integrations" };

const STATUS_TONE = {
  NOT_CONFIGURED: "neutral",
  CONNECTED: "success",
  ERROR: "danger",
  DISABLED: "warning",
} as const;

export default async function IntegrationsSettingsPage() {
  const ctx = await requireOrgContext();
  if (!can(ctx.role, "integration:manage")) {
    return <DeniedState message="Only owners and admins manage integrations." />;
  }

  const summary = await getInvoiceIntegration(ctx.org.id);
  const base = process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") || "http://localhost:3000";
  const webhookUrl = `${base}/api/integrations/invoice/webhook?org=${ctx.org.id}`;

  const recentEvents = await prisma.integrationEvent.findMany({
    where: { orgId: ctx.org.id },
    orderBy: { receivedAt: "desc" },
    take: 8,
  });

  return (
    <div>
      <Link href="/settings" className="mb-4 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground">
        <ChevronLeft className="size-4" /> Settings
      </Link>
      <PageHeader
        title="Integrations"
        description="Connect Dotnapps Invoice. CRM owns the relationship; Dotnapps Invoice stays the financial source of truth."
      />

      <Card className="mb-6">
        <CardHeader className="flex flex-row items-center justify-between space-y-0">
          <CardTitle>Dotnapps Invoice</CardTitle>
          <div className="flex items-center gap-2">
            <Badge tone={STATUS_TONE[summary.status]}>{summary.status.replace("_", " ").toLowerCase()}</Badge>
            {summary.configured && <Badge tone="neutral">{summary.mode.toLowerCase()} mode</Badge>}
          </div>
        </CardHeader>
        <CardContent>
          {summary.mode === "MOCK" && summary.configured && (
            <p className="mb-4 rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-200">
              Sandbox mode — quotations, invoices and payments shown in the CRM
              are generated by a built-in mock, not a real Dotnapps Invoice
              account. Switch to Live to connect real billing.
            </p>
          )}
          {summary.lastError && (
            <p className="mb-4 text-sm text-destructive">
              Last check failed: {summary.lastError}
              {summary.lastCheckedAt ? ` (${formatDate(summary.lastCheckedAt)})` : ""}
            </p>
          )}

          <IntegrationForm summary={summary} webhookUrl={webhookUrl} />

          {summary.configured && (
            <div className="mt-6 flex flex-wrap gap-2 border-t border-border pt-4">
              <form action={setInvoiceEnabledAction}>
                <input type="hidden" name="enable" value={(summary.status !== "CONNECTED").toString()} />
                <button className={buttonClassName({ variant: "outline", size: "sm" })}>
                  {summary.status === "CONNECTED" ? "Disable" : "Enable"}
                </button>
              </form>
              <form action={disconnectInvoiceAction}>
                <button className={buttonClassName({ variant: "outline", size: "sm" })}>
                  Disconnect
                </button>
              </form>
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader><CardTitle>Recent webhook events</CardTitle></CardHeader>
        <CardContent className="p-0">
          {recentEvents.length === 0 ? (
            <p className="px-5 py-6 text-sm text-muted-foreground">
              No events received yet.
            </p>
          ) : (
            <ul className="divide-y divide-border">
              {recentEvents.map((e) => (
                <li key={e.id} className="flex flex-wrap items-center gap-x-3 gap-y-1 px-5 py-2.5 text-sm">
                  <code className="text-xs">{e.eventType}</code>
                  <Badge
                    tone={e.status === "PROCESSED" ? "success" : e.status === "IGNORED" ? "neutral" : "danger"}
                  >
                    {e.status.toLowerCase()}
                  </Badge>
                  {e.error && <span className="text-xs text-destructive">{e.error}</span>}
                  <span className="ml-auto text-xs text-muted-foreground">
                    {e.receivedAt.toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
